"""Sales dashboard graphical interface module.

This module provides a dedicated PySide6 dashboard window for displaying
previously calculated sales-analysis results and generated chart images.

The dashboard presents general sales KPIs, highlighted best-performing
results, and an interactive chart selector that allows the user to display
generated sales charts directly inside the window.

The module receives the structured `analysis_result` produced by the sales
analysis workflow and the chart-path dictionary generated by the chart manager.

It does not calculate sales metrics, generate charts, validate data, or read
source files. Its responsibility is limited to presenting existing analysis
results through a graphical dashboard.
"""


from typing import Dict, Any, List
from PySide6.QtGui import QPixmap
from PySide6.QtCore import Qt
from PySide6.QtWidgets import(
    QMainWindow,
    QWidget,
    QVBoxLayout,
    QLabel,
    QHBoxLayout,
    QComboBox,
    QFrame,
)

class DashboardWindow(QMainWindow):
    """Sales-analysis dashboard window.

    Displays key sales indicators, highlighted best-performing results, and
    generated chart images using data produced by the backend analysis and
    chart-generation workflows.

    The dashboard receives already calculated sales information and generated
    chart paths from the main graphical interface. It does not perform sales
    analysis or generate chart files itself.

    The window contains three primary areas:

    - General KPI cards.
    - Best-result cards.
    - Interactive chart visualization.

    Attributes:
        analysis_result: Dictionary containing the structured sales-analysis
            result generated by the analysis module.
        chart_paths: Dictionary mapping chart identifiers to generated chart
            file paths.
        chart_image: Label used to display the currently selected chart image.
        combo_box: Combo box used to select the chart displayed in the
            dashboard.
    """
    def __init__(self, analysis_result: Dict[str, Any], chart_paths: Dict[str, Any]) -> None:
        """Initialize the sales dashboard window.

        Stores the structured sales-analysis result and generated chart paths,
        configures the dashboard window, creates the central widget, and builds
        the main dashboard layout.

        The dashboard is organized into:

        - General sales KPI cards.
        - Best-performing result cards.
        - Interactive chart visualization.

        Args:
            analysis_result: Dictionary containing previously calculated sales
                metrics, summaries, and rankings.
            chart_paths: Dictionary mapping generated chart identifiers to their
                corresponding file paths.
        """
        super().__init__()
        self.analysis_result = analysis_result
        self.chart_paths = chart_paths
        self.setWindowTitle("Panel de ventas")
        self.setFixedSize(1500, 900)

        central_widget = QWidget()

        main_layout = QVBoxLayout()

        main_layout.addLayout(self.build_general_kpis_layout())
        main_layout.addLayout(self.build_best_result_layout())
        main_layout.addLayout(self.build_charts_layout())
        central_widget.setLayout(main_layout)
        self.setCentralWidget(central_widget)

    def create_kpi_card(self, title: str, value: str) -> QFrame:
        """Create a dashboard card for displaying a general KPI.

        Creates a framed widget containing a KPI title and its corresponding value.

        Both labels are centered and styled using bold Arial typography. The KPI
        value uses a larger font size to visually emphasize the metric.

        Args:
            title: Human-readable title of the KPI.
            value: Formatted KPI value displayed in the card.

        Returns:
            A `QFrame` containing the formatted KPI title and value.
        """
        frame = QFrame()
        frame.setFrameShape(QFrame.Shape.Box)
        layout_frame = QVBoxLayout()
        title_label = QLabel(title)
        title_label.setStyleSheet("""
        font-size: 20px;
        font-weight: bold;
        font-family: Arial;
        """)
        value_label = QLabel(value)
        value_label.setStyleSheet("""
        font-size: 30px;
        font-weight: bold;
        font-family: Arial;
        """)
        layout_frame.addWidget(title_label, alignment=Qt.AlignmentFlag.AlignCenter)
        layout_frame.addWidget(value_label, alignment=Qt.AlignmentFlag.AlignCenter)
        frame.setLayout(layout_frame)
        return frame

    def build_general_kpis_layout(self) -> QHBoxLayout:
        """Build the general sales KPI section.

        Creates a horizontal layout containing summary cards for the primary
        sales-analysis metrics.

        The section currently displays:

        - Total income.
        - Total units sold.
        - Total valid rows.
        - Total invalid rows.

        Total income is formatted as currency using thousands separators and two
        decimal places.

        Each metric is converted into a visual card through `create_kpi_card()`.

        Returns:
            A `QHBoxLayout` containing the general KPI cards.
        """
        layout = QHBoxLayout()
        summary = {
            "INGRESO TOTAL": f'${self.analysis_result["total_income"]:,.2f}',
            "UNIDADES VENDIDAS": f'{self.analysis_result["total_units_sold"]}',
            "FILAS VÁLIDAS": f'{self.analysis_result["total_valid_rows"]}',
            "FILAS INVÁLIDAS": f'{self.analysis_result["total_invalid_rows"]}'
        }
        for key, value in summary.items():
            frame = self.create_kpi_card(key, value)
            layout.addWidget(frame)
        return layout

    def create_result_card(self, title: str, list_values: List[List[str]]) -> QFrame:
        """Create a dashboard card for highlighted analysis results.

        Creates a framed widget containing a section title and one or more groups
        of result values.

        The nested list structure allows multiple values to be displayed for each
        result and also supports tied analysis records when more than one record
        shares the same maximum value.

        Every displayed value is rendered as an independent centered label using
        bold Arial typography.

        Args:
            title: Human-readable title displayed at the top of the card.
            list_values: Nested list containing the formatted values that will be
                displayed inside the result card.

        Returns:
            A `QFrame` containing the formatted result information.
        """
        frame = QFrame()
        frame.setFrameShape(QFrame.Shape.Box)
        layout_frame = QVBoxLayout()
        title_label = QLabel(title)
        title_label.setStyleSheet("""
        font-size: 20px;
        font-weight: bold;
        font-family: Arial;
        """)
        layout_frame.addWidget(title_label, alignment=Qt.AlignmentFlag.AlignCenter)
        for result in list_values:
            for value in result:
                value_label = QLabel(value)
                value_label.setStyleSheet("""
                font-size: 30px;
                font-weight: bold;
                font-family: Arial;
                """)
                layout_frame.addWidget(value_label, alignment=Qt.AlignmentFlag.AlignCenter)
        frame.setLayout(layout_frame)
        return frame

    def build_best_result_layout(self) -> QHBoxLayout:
        """Build the highlighted best-performing results section.

        Creates a horizontal layout containing cards for the primary maximum-value
        sales results calculated by the analysis module.

        The section currently displays:

        - Best-selling product or products.
        - Highest-income product or products.
        - Highest-income category or categories.

        The underlying analysis structures are lists, so tied records are
        preserved and displayed when multiple products or categories share the
        same maximum value.

        Product unit values are displayed as unit counts, while income values are
        formatted as currency using thousands separators and two decimal places.

        Returns:
            A `QHBoxLayout` containing the highlighted result cards.
        """
        layout = QHBoxLayout()
        summary = {
            "PRODUCTO MÁS VENDIDO": [[product.get("producto"), f'{product.get("unidades_vendidas")} Unidades.'] for product in self.analysis_result["best_selling_product"]],
            "PRODUCTO CON MAYOR INGRESO": [[product.get("producto"), f'${product.get("ingreso_total"):,.2f}'] for product in self.analysis_result["highest_income_product"]],
            "CATEGORÍA CON MAYOR INGRESO": [[category.get("categoria"), f'${category.get("ingreso_total"):,.2f}'] for category in self.analysis_result["highest_income_category"]]
        }
        for key, value in summary.items():
            frame = self.create_result_card(key, value)
            layout.addWidget(frame)
        return layout

    def create_chart_card(self) -> QFrame:
        """Create the interactive chart visualization card.

        Creates a framed dashboard section containing a chart selector and an
        image area used to display the currently selected chart.

        The chart selector is populated using the identifiers contained in
        `chart_paths`.

        The first available chart is displayed when the card is created.

        The combo box `currentTextChanged` signal is connected to
        `show_chart_card()`, allowing the displayed chart to update whenever the
        user selects another chart.

        Returns:
            A `QFrame` containing the chart selector and chart display area.
        """
        frame = QFrame()
        frame.setFrameShape(QFrame.Shape.Box)
        main_layout_frame = QVBoxLayout()
        layout_frame = QHBoxLayout()
        self.chart_image = QLabel()
        chart_label = QLabel("Gráfica:")
        chart_label.setStyleSheet("""
        font-size: 20px;
        font-weight: bold;
        font-family: Arial;
        """)
        layout_frame.addWidget(chart_label, alignment=Qt.AlignmentFlag.AlignHCenter)
        self.combo_box = QComboBox()
        for name_path, _ in self.chart_paths.items():
            self.combo_box.addItem(name_path)
        self.combo_box.setStyleSheet("""
        QComboBox {
        font-size: 12pt;
        font-weight: bold;
        font-family: Arial;
        }
        """)
        self.show_chart_card(self.combo_box.currentText())
        self.combo_box.currentTextChanged.connect(self.show_chart_card)
        layout_frame.addWidget(self.combo_box)
        main_layout_frame.addLayout(layout_frame)
        main_layout_frame.addWidget(self.chart_image, alignment=Qt.AlignmentFlag.AlignCenter)
        frame.setLayout(main_layout_frame)
        return frame
    
    def build_charts_layout(self) -> QHBoxLayout:
        """Build the dashboard chart section.

        Creates a horizontal layout containing the interactive chart card produced
        by `create_chart_card()`.

        Returns:
            A `QHBoxLayout` containing the chart visualization controls.
        """
        layout = QHBoxLayout()
        layout.addWidget(self.create_chart_card())
        return layout

    def show_chart_card(self, path_chart: str) -> None:
        """Display the selected generated chart inside the dashboard.

        Receives a chart identifier selected through the dashboard combo box and
        retrieves its corresponding image path from `chart_paths`.

        The chart file is loaded into a `QPixmap` and scaled to fit within a
        500-by-400-pixel area while preserving its original aspect ratio.

        Smooth transformation is used during scaling to improve visual quality.

        If the supplied chart identifier is empty, no image update is performed.

        Args:
            path_chart: Identifier of the chart selected in the dashboard combo
                box.

        Returns:
            None.
        """
        if path_chart.strip() != "":
            pixmap = QPixmap(str(self.chart_paths[path_chart]))
            pixmap_scale = pixmap.scaled(500, 400, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation)
            self.chart_image.setPixmap(pixmap_scale)
