"""Sales data analysis module.

This module processes previously validated sales records and calculates
general sales metrics, product summaries, category summaries, monthly
performance metrics, and optional city and payment-method summaries.

Each analysis operation is implemented in an independent helper function to
keep the analysis workflow modular, maintainable, and easy to extend.

The module also generates Top 5 product rankings, identifies records tied
for maximum values, calculates monthly income and unit growth, and determines
the best-selling product and highest-income category for each month.

The main `analyze_sales()` function coordinates the independent analysis
helpers and returns a structured dictionary ready for report generation,
chart generation, and file export.
"""

from typing import Dict, Any, List
import pandas as pd
import numpy as np
from src.errors import NoValidRowsError

def create_income_column(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Calculate the income generated by each sales record.

    Creates the `ingreso_fila` column by multiplying the `precio` value by the 
    `cantidad` value in every row.

    The provided DataFrame is modified directly and returned with the new 
    calculated column.

    Args:
        df_analysis: DataFrame containing validated sales records with numeric
            `precio` and `cantidad` columns.

    Returns:
        The same DataFrame with the `ingreso_fila` column added.
    """
    df_analysis["ingreso_fila"] = df_analysis["precio"] * df_analysis["cantidad"]
    return df_analysis

def get_total_income(df_analysis: pd.DataFrame) -> float:
    """Calculate the total income generated by valid sales records.

    Adds all values from the `ingreso_fila` column and converts the result
    to a standard Python float.

    Args:
        df_analysis: DataFrame containing the calculated `ingreso_fila`
            column.

    Returns:
        The total income generated by all valid sales records.
    """
    total_income = float(df_analysis["ingreso_fila"].sum())
    return total_income

def get_total_units_sold(df_analysis: pd.DataFrame) -> int:
    """Calculate the total number of units sold.

    Adds all values from the `cantidad` column and converts the result to
    a standard Python integer.

    Args:
        df_analysis: DataFrame containing valid sales records with a numeric 
        `cantidad` column.

    Returns:
        The total number of units sold across all valid records.
    """
    total_units_sold = int(df_analysis["cantidad"].sum())
    return total_units_sold

def get_product_summary(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Create an aggregated sales summary grouped by product.

    Groups valid sales records by `producto_id` and calculates the total
    units sold and total income for each product. The first product name
    and category associated with each identifier are preserved.

    The aggregated columns are renamed to `unidades_vendidas` and
    `ingreso_total`.

    The resulting records are sorted from highest to lowest total income.

    Args:
        df_analysis: DataFrame containing valid sales records and the
            calculated `ingreso_fila` column.

    Returns:
        A DataFrame containing one row per product with the following columns:

        - `producto_id`: Unique product identifier.
        - `producto`: Product name.
        - `categoria`: Product category.
        - `unidades_vendidas`: Total units sold for the product.
        - `ingreso_total`: Total income generated by the product.
    """
    df_product_summary = df_analysis.groupby("producto_id").agg({
        "producto": "first",
        "categoria": "first",
        "cantidad": "sum",
        "ingreso_fila": "sum"
    }).reset_index()
    df_product_summary = df_product_summary.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    })
    df_product_summary = df_product_summary.sort_values(by="ingreso_total", ascending=False).reset_index(drop=True)
    return df_product_summary

def get_category_summary(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Create an aggregated sales summary grouped by category.

    Groups valid sales records by `categoria` and calculates the total
    units sold and total income generated by each category.

    The aggregated columns are renamed to `unidades_vendidas` and
    `ingreso_total`.

    The resulting records are sorted from highest to lowest total income.

    Args:
        df_analysis: DataFrame containing valid sales records and the
            calculated `ingreso_fila` column.

    Returns:
        A DataFrame containing one row per category with the following columns:

        - `categoria`: Product category.
        - `unidades_vendidas`: Total units sold in the category.
        - `ingreso_total`: Total income generated by the category.
    """
    df_category_summary = df_analysis.groupby("categoria").agg({
        "cantidad": "sum",
        "ingreso_fila": "sum"
    }).reset_index()
    df_category_summary = df_category_summary.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    })
    df_category_summary = df_category_summary.sort_values(by="ingreso_total", ascending=False).reset_index(drop=True)
    return df_category_summary

def get_city_summary(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Create an aggregated sales summary gruped by city.

    Filters out records with empty `ciudad` values and groups the remaining
    sales records by city. It calculates the total units sold and total income
    for each city.

    the resulting records are sorted from highest to lowest total income.

    Args:
        df_analysis: DataFrame containing valid sales records the optional
            `ciudad` column, and the calculated `ingreso_fila` column.

    Returns:
        A DataFrame containin one row per city with the following columns:

        - `ciudad`: City associated with the sales records.
        - `unidades_vendidas`: Total units sold in the city.
        - `ingreso_total`: Total income gtenerated in the city.
    """
    df_city_summary = df_analysis[df_analysis["ciudad"].str.strip() != ""]
    df_city_summary = df_city_summary.groupby("ciudad").agg({
        "cantidad": "sum",
        "ingreso_fila": "sum"
    }).reset_index()
    df_city_summary = df_city_summary.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    })
    df_city_summary = df_city_summary.sort_values(by="ingreso_total", ascending=False).reset_index(drop=True)
    return df_city_summary

def get_payment_method_summary(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Create an aggregated sales summary grouped by payment method.

    Filters out records with empty `metodo_pago` values and groups the 
    remaining sales records by payment method. It calculates the total
    units sold and total income for each payment method.

    The resulting records are sorted form highest ot lowest total income.

    Args:
        df_analysis: Data Frame containing valid sales records, the optional
            `metodo_pago` column, and the calculated `ingreso_fila` column.

    Returns:
        A DataFrame containing one row per payment method with the followin columns:

        - `metodo_pago`: Payment method associated with the sales recordsds.
        - `unidades_vendidas`: Total units sold using the payment method.
        - `ingreso_total`: Total income generated using the payment method.
    """
    df_payment_method = df_analysis[df_analysis["metodo_pago"].str.strip() != ""]
    df_payment_method = df_payment_method.groupby("metodo_pago").agg({
        "metodo_pago": "first",
        "cantidad": "sum",
        "ingreso_fila": "sum"
    })
    df_payment_method = df_payment_method.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    })
    df_payment_method = df_payment_method.sort_values(by="ingreso_total", ascending=False).reset_index(drop=True)
    return df_payment_method

def get_records_with_max_value(df: pd.DataFrame, column_name : str) -> List[Dict[str, Any]]:
    """Return all records containing the maximum value in a column.

    Determines the highest value in the specified column and selects every
    row containing that value. All tied records are preserved.

    The selected rows are converted into a list of dictionaries for easier
    report generation.

    Args:
        df: DataFrame containing the records to compare.
        column_name: Name of the numeric column used to determine the 
            maximum value.

    Returns:
        A list of dictionaries containing all records tied for the maximum
        value in the specified column.
    """
    df_max = df[df[column_name] == df[column_name].max()]
    return df_max.to_dict(orient="records")

def get_top_5(product_summary: pd.DataFrame, by_str: str | List[str], ascending_bool: bool | List[bool]) -> List[Dict[str, Any]]:
    """Return up to five products sorted by the specified criteria.

    Sorts the product-summary DataFrame using one or more columns and the
    corresponding sort directions. The first five records from the sorted
    result are returned.

    This helper can be reused to generate different Top 5 product rankings,
    such as best-selling products or highest-income products.

    Args:
        product_summary: DataFrame containing aggregated product results.
        by_str: Column name or list of column names used for sorting.
        ascending_bool: Boolean or list of booleans defining the sort
            direction for each sorting column.

    Returns:
        A list of dictionaries containing up to five sorted product records.
    """
    df_top5 = product_summary.sort_values(by=by_str, ascending=ascending_bool).head(5).reset_index(drop=True)
    return df_top5.to_dict(orient="records")

def get_income_growth_units(df_analysis: pd.DataFrame, new_column: str, process_column: str) -> pd.DataFrame:
    """Calculate absolute growth between consecutive records.

    Creates a new column by subtracting the previous row value from the
    current row value in the specified processing column.

    The first row receives a missing value because no previous record is
    available for comparison.

    This helper is used to calculate absolute monthly growth for income and
    units sold.

    Args:
        df_analysis: DataFrame containing the values to compare.
        new_column: Name of the column where the calculated growth values
            will be stored.
        process_column: Name of the numeric column used to calculate growth.

    Returns:
        The DataFrame with the new absolute-growth column added.
    """
    df_analysis[new_column] = df_analysis[process_column] - df_analysis[process_column].shift(1)
    return df_analysis

def get_income_percentage_growth(df_analysis: pd.DataFrame, new_column: str, process_column: str) -> pd.DataFrame:
    """Calculate percentage growth between consecutive records.

    Calculates the percentage change of the specified numeric column and
    stores the result in a new column.

    Infinite values produced by percentage calculations are replaced with
    missing values, and the final percentages are rounded to two decimal
    places.

    This helper is used to calculate monthly percentage growth for income
    and units sold.

    Args:
        df_analysis: DataFrame containing the values to compare.
        new_column: Name of the column where percentage-growth values will
            be stored.
        process_column: Name of the numeric column used to calculate
            percentage growth.

    Returns:
        The DataFrame with the new percentage-growth column added.
    """
    df_analysis[new_column] = df_analysis[process_column].pct_change() * 100
    df_analysis[new_column] = df_analysis[new_column].replace([np.inf, -np.inf], np.nan)
    df_analysis[new_column] = df_analysis[new_column].round(2)
    return df_analysis
    
def get_monthly_summary(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Create an aggregated monthly sales summary.

    Creates a copy of the sales DataFrame, converts the `fecha` column into
    `YYYY-MM` month identifiers, and groups valid sales records by month.

    For each month, the function calculates the number of valid sales rows,
    total units sold, and total income generated.

    The resulting records are sorted chronologically from the earliest month
    to the latest month.

    After aggregation, the function also calculates absolute and percentage
    growth between consecutive months for both income and units sold.

    Args:
        df_analysis: DataFrame containing valid sales records, a datetime
            `fecha` column, and the calculated `ingreso_fila` column.

    Returns:
        A DataFrame containing one row per month with the following columns:

        - `mes`: Month represented in `YYYY-MM` format.
        - `filas_validas`: Number of valid sales records for the month.
        - `unidades_vendidas`: Total units sold during the month.
        - `ingreso_total`: Total income generated during the month.
        - `crecimiento_ingreso`: Absolute income change from the previous month.
        - `crec_ingreso_pct`: Percentage income change from the
        previous month.
        - `crecimiento_unidades`: Absolute unit-sales change from the previous
        month.
        - `crec_unidades_pct`: Percentage unit-sales change from
        the previous month.
    """
    df_analysis_copy = df_analysis.copy()
    df_analysis_copy["mes"] = df_analysis_copy["fecha"].dt.strftime("%Y-%m")
    df_monthly = df_analysis_copy.groupby("mes").agg({
        "producto_id": "count",
        "cantidad": "sum",
        "ingreso_fila": "sum",
    })
    df_monthly = df_monthly.rename(columns={
        "producto_id": "filas_validas",
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
        })
    df_monthly = df_monthly.sort_values(by="mes", ascending=True).reset_index()
    df_monthly = get_income_growth_units(df_monthly, "crecimiento_ingreso", "ingreso_total")
    df_monthly = get_income_percentage_growth(df_monthly, "crec_ingreso_pct", "ingreso_total")
    df_monthly = get_income_growth_units(df_monthly, "crecimiento_unidades", "unidades_vendidas")
    df_monthly = get_income_percentage_growth(df_monthly, "crec_unidades_pct", "unidades_vendidas")
    return df_monthly

def get_monthly_best_selling_product(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Identify the best-selling product for each month.

    Creates a monthly product aggregation using `mes` and `producto_id`.
    For each product and month, it calculates total units sold and total
    income while preserving the associated product name and category.

    The maximum number of units sold is calculated independently for each
    month. Every product tied for that monthly maximum is preserved.

    Args:
        df_analysis: DataFrame containing valid sales records, a datetime
            `fecha` column, and the calculated `ingreso_fila` column.

    Returns:
        A DataFrame containing the best-selling product or products for each
        month, including:

        - `mes`
        - `producto_id`
        - `producto`
        - `categoria`
        - `unidades_vendidas`
        - `ingreso_total`
    """
    df_analysis_copy = df_analysis.copy()
    df_analysis_copy["mes"] = df_analysis_copy["fecha"].dt.strftime("%Y-%m")
    df_month_id_product = df_analysis_copy.groupby(["mes", "producto_id"]).agg({
        "producto": "first",
        "categoria": "first",
        "cantidad": "sum",
        "ingreso_fila": "sum"
    })
    df_month_id_product = df_month_id_product.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    }).reset_index()
    max_units_month = df_month_id_product.groupby("mes")["unidades_vendidas"].transform("max")
    top_products = df_month_id_product[df_month_id_product["unidades_vendidas"] == max_units_month]
    return top_products.reset_index(drop=True)

def get_monthly_highest_income_category(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Identify the highest-income category for each month.

    Creates a monthly category aggregation using `mes` and `categoria`.

    For each category and month, it calculates total units sold and total
    income. The maximum income value is then calculated independently for
    each month.

    Every category tied for the highest monthly income is preserved.

    Args:
        df_analysis: DataFrame containing valid sales records, a datetime
            `fecha` column, and the calculated `ingreso_fila` column.

    Returns:
        A DataFrame containing the highest-income category or categories for
        each month, including:

        - `mes`
        - `categoria`
        - `unidades_vendidas`
        - `ingreso_total`
    """
    df_analysis_copy = df_analysis.copy()
    df_analysis_copy["mes"] = df_analysis_copy["fecha"].dt.strftime("%Y-%m")
    df_month_category = df_analysis_copy.groupby(["mes", "categoria"]).agg({
        "cantidad": "sum",
        "ingreso_fila": "sum"
    })
    df_month_category = df_month_category.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    }).reset_index()
    max_income_month = df_month_category.groupby("mes")["ingreso_total"].transform("max")
    top_categories = df_month_category[df_month_category["ingreso_total"] == max_income_month]
    return top_categories.reset_index(drop=True)

def analyze_sales(validation_result: Dict[str, Any]) -> Dict[str, Any]:
    """Analyze validated sales records and calculate summary metrics.

        Receives the result produced by the DataFrame validation process, extracts
        the valid sales records, and coordinates the independent analysis helper
        functions.

        The function calculates row-level income, total income, total units sold,
        product summaries, category summaries, and monthly sales summaries.

        The monthly analysis also includes absolute and percentage growth for income
        and units sold, the best-selling product or products for each month, and the
        highest-income category or categories for each month.

        The function identifies overall best-selling products, highest-income
        products, and highest-income categories. It also generates reusable Top 5
        product rankings.

        If the optional `ciudad` column is available, the function generates a city
        summary and identifies the city or cities with the highest total income.

        If the optional `metodo_pago` column is available, the function generates a
        payment-method summary and identifies the payment method or methods with the
        highest total income.

        Args:
            validation_result: Dictionary produced by the validation process.
                It must contain:

                - `df_valid_rows`: DataFrame containing valid sales records.
                - `total_rows`: Total number of processed records.
                - `total_valid_rows`: Number of records that passed validation.
                - `total_invalid_rows`: Number of records containing validation
                errors.

        Returns:
            A dictionary containing the calculated sales analysis results.

            The result always contains:

            - `total_rows`: Total number of processed records.
            - `total_valid_rows`: Number of valid records.
            - `total_invalid_rows`: Number of invalid records.
            - `total_income`: Total income generated by valid sales.
            - `total_units_sold`: Total number of units sold.
            - `product_summary`: DataFrame containing aggregated product results.
            - `category_summary`: DataFrame containing aggregated category results.
            - `monthly_summary`: DataFrame containing monthly sales totals and
            growth metrics.
            - `best_selling_product`: List containing the product or products tied
            for the highest number of units sold.
            - `highest_income_product`: List containing the product or products tied
            for the highest total income.
            - `highest_income_category`: List containing the category or categories
            tied for the highest total income.
            - `top_5_best_selling_products`: List containing up to five products
            ranked by units sold and total income.
            - `top_5_highest_income_products`: List containing up to five products
            ranked by total income.
            - `monthly_best_selling_product`: DataFrame containing the best-selling
            product or products for each month.
            - `monthly_highest_income_category`: DataFrame containing the
            highest-income category or categories for each month.

            When the optional `ciudad` column is available, the result also contains:

            - `city_summary`: DataFrame containing aggregated city results.
            - `highest_income_city`: List containing the city or cities tied for the
            highest total income.

            When the optional `metodo_pago` column is available, the result also
            contains:

            - `payment_method_summary`: DataFrame containing aggregated
            payment-method results.
            - `highest_income_payment_method`: List containing the payment method or
            methods tied for the highest total income.

        Raises:
            NoValidRowsError: If no valid sales records are available for analysis.
        """
    df_valid_rows = validation_result["df_valid_rows"]
    total_rows = validation_result["total_rows"]
    total_valid_rows = validation_result["total_valid_rows"]
    total_invalid_rows = validation_result["total_invalid_rows"]
    analysis_result = {
        "total_rows": total_rows,
        "total_valid_rows": total_valid_rows,
        "total_invalid_rows": total_invalid_rows,
    }
    df_analysis = df_valid_rows.copy()
    if len(df_analysis) < 1:
        raise NoValidRowsError()
    df_analysis = create_income_column(df_analysis)
    analysis_result["total_income"] = get_total_income(df_analysis)
    analysis_result["total_units_sold"] = get_total_units_sold(df_analysis)
    analysis_result["product_summary"] = get_product_summary(df_analysis)
    analysis_result["category_summary"] = get_category_summary(df_analysis)
    analysis_result["monthly_summary"] = get_monthly_summary(df_analysis)
    analysis_result["best_selling_product"] = get_records_with_max_value(analysis_result["product_summary"], "unidades_vendidas")
    analysis_result["highest_income_product"] = get_records_with_max_value(analysis_result["product_summary"], "ingreso_total")
    analysis_result["highest_income_category"] = get_records_with_max_value(analysis_result["category_summary"], "ingreso_total")
    analysis_result["top_5_best_selling_products"] = get_top_5(analysis_result["product_summary"], ["unidades_vendidas", "ingreso_total"], [False, False])
    analysis_result["top_5_highest_income_products"] = get_top_5(analysis_result["product_summary"], "ingreso_total", False)
    analysis_result["monthly_best_selling_product"] = get_monthly_best_selling_product(df_analysis)
    analysis_result["monthly_highest_income_category"] = get_monthly_highest_income_category(df_analysis)
    if "ciudad" in df_analysis.columns:
        analysis_result["city_summary"] = get_city_summary(df_analysis)
        analysis_result["highest_income_city"] = get_records_with_max_value(analysis_result["city_summary"], "ingreso_total")
    if "metodo_pago" in df_analysis.columns:
        analysis_result["payment_method_summary"] = get_payment_method_summary(df_analysis)
        analysis_result["highest_income_payment_method"] = get_records_with_max_value(analysis_result["payment_method_summary"], "ingreso_total")
    return analysis_result
