"""Sales data analysis module.

This module processes previously validated sales records and calculates
general sales metrics, product, category, and optional city summaries.

Each analysis operation is impolemented in a separate helper function to
keep the analysis workflow modular, maintaiable, and easy to extend.
The module also generates Top 5 prouct rankings and indentifies records with the highest values.

The main analysis funciton coordinates these gelpers and returns a
structured dictionay ready for report generation.
"""

from typing import Dict, Any, List
import pandas as pd
from src.errors import NoValidRowsError

def create_income_column(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Calculate the income generated by each sales record.

    Creates the `ingreso_fila` column by multiplying the `precio` value by the 
    `cantidad` value in every row.

    The provided DataFrame is modified directly and returned with the new 
    calculated column.

    Args:
        df_analysis: DataFrame containing validated sales records with numeric
            `precio` and `cantidad` columns.

    Returns:
        The same DataFrame with the `ingreso_fila` column added.
    """
    df_analysis["ingreso_fila"] = df_analysis["precio"] * df_analysis["cantidad"]
    return df_analysis

def get_total_income(df_analysis: pd.DataFrame) -> float:
    """Calculate the total income generated by valid sales records.

    Adds all values from the `ingreso_fila` column and converts the result
    to a standard Python float.

    Args:
        df_analysis: DataFrame containing the calculated `ingreso_fila`
            column.

    Returns:
        The total income generated by all valid sales records.
    """
    total_income = float(df_analysis["ingreso_fila"].sum())
    return total_income

def get_total_units_sold(df_analysis: pd.DataFrame) -> int:
    """Calculate the total number of units sold.

    Adds all values from the `cantidad` column and converts the result to
    a standard Python integer.

    Args:
        df_analysis: DataFrame containing valid sales records with a numeric 
        `cantidad` column.

    Returns:
        The total number of units sold across all valid records.
    """
    total_units_sold = int(df_analysis["cantidad"].sum())
    return total_units_sold

def get_product_summary(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Create an aggregated sales summary grouped by product.

    Groups valid sales records by `producto_id` and calculates the total
    units sold and total income for each product. The first product name
    and category associated with each identifier are preserved in the result.

    The aggregated columns are renamed to `unidades_vendidas` and 
    `ingreso_total`

    Args:
        df_analysis: DataFrame containing valid sales records and the
            calculated `ingreso_fila` column.

    Returns:
        A DataFrame containing one row per product with the following columns:

        - `producto_id`: Unique product identifier.
        - `producto`: Product name.
        - `categoria`: Product category.
        - `unidades_vendidas`: Total units sold for the product.
        - `ingreso_total`: Total income generated by the product.
    """
    df_product_summary = df_analysis.groupby("producto_id").agg({
        "producto": "first",
        "categoria": "first",
        "cantidad": "sum",
        "ingreso_fila": "sum"
    }).reset_index()
    df_product_summary = df_product_summary.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    })
    return df_product_summary

def get_category_summary(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Create an aggregated sales summary grouped by category.

    Groups valid sales records by `categoria` and calculates the total 
    units sold and total income generated by each category.

    The aggregated columns are renamed to `unidades_vendidas` and
    `ingreso_total`.

    Args:
        df_analysis: DataFrame containing valid sales records and the
            calculated `ingreso_fila` column.

    Returns:
        A DataFrame containing one row per category with the following columns:

        - `categoria`: Product category.
        - `unidades_vendidas`: Total units sold in the category.
        - `ingreso_total`: Total income generated by the category.
    """
    df_category_summary = df_analysis.groupby("categoria").agg({
        "cantidad": "sum",
        "ingreso_fila": "sum"
    }).reset_index()
    df_category_summary = df_category_summary.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    })
    return df_category_summary

def get_city_summary(df_analysis: pd.DataFrame) -> pd.DataFrame:
    """Create an aggregated sales summary gruped by city.

    Filters out records with empty `ciudad` values and groups the remaining
    sales records by city. It calculates the total units sold and total income
    for each city.

    the resulting records are sorted from highest to lowest total income.

    Args:
        df_analysis: DataFrame containing valid sales records the optional
            `ciudad` column, and the calculated `ingreso_fila` column.

    Returns:
        A DataFrame containin one row per city with the following columns:

        - `ciudad`: City associated with the sales records.
        - `unidades_vendidas`: Total units sold in the city.
        - `ingreso_total`: Total income gtenerated in the city.
    """
    df_city_summary = df_analysis[df_analysis["ciudad"].str.strip() != ""]
    df_city_summary = df_city_summary.groupby("ciudad").agg({
        "cantidad": "sum",
        "ingreso_fila": "sum"
    }).reset_index()

    df_city_summary = df_city_summary.rename(columns={
        "cantidad": "unidades_vendidas",
        "ingreso_fila": "ingreso_total"
    })
    df_city_summary = df_city_summary.sort_values(by="ingreso_total", ascending=False).reset_index(drop=True)
    return df_city_summary


def get_records_with_max_value(df: pd.DataFrame, column_name : str) -> List[Dict[str, Any]]:
    """Return all records containing the maximum value in a column.

    Determines the highest value in the specified column and selects every
    row containing that value. All tied records are preserved.

    The selected rows are converted into a list of dictionaries for easier
    report generation.

    Args:
        df: DataFrame containing the records to compare.
        column_name: Name of the numeric column used to determine the 
            maximum value.

    Returns:
        A list of dictionaries containing all records tied for the maximum
        value in the specified column.
    """
    df_max = df[df[column_name] == df[column_name].max()]
    return df_max.to_dict(orient="records")

def get_top_5_best_selling_products(product_summary: pd.DataFrame) -> List[Dict[str, Any]]:
    """Return the Top 5 best-selling products.

    Sorts the product summary by total units sold in descending order.
    When products have the same number of units sold, total income is used
    as a secundary sortin criterion.

    Args:
        product_summary: DataFrame containing aggregated sales information
            for each product.

    Returns:
        a list of dictionaries containing up to five products with the
        highest number of units sold.
    """
    df_top5 = product_summary.sort_values(by=["unidades_vendidas", "ingreso_total"], ascending=[False,False]).head(5).reset_index(drop=True)
    return df_top5.to_dict(orient="records")

def get_top_5_highest_income_products(product_summary: pd.DataFrame) -> List[Dict[str, Any]]:
    """Return the Top 5 products with the highest total income.

    Sorts the product summary by `ingreso_total` in descending order and
    selects up to the first five records.

    Args:
        product_summary: DataFrame contianin aggregated sales infomation for each product.

    Returns:
        A list of dictionaries containing up to five products with the highest total income.
    """
    df_top5 = product_summary.sort_values(by="ingreso_total", ascending=False).head(5).reset_index(drop=True)
    return df_top5.to_dict(orient="records")

def analyze_sales(validation_result: Dict[str, Any]) -> Dict[str, Any]:
    """Analyze validated sales records and calculate summary metrics.

    Receives the result produced by the DataFrame validation process,
    extracts the valid sales records, and coordinates the independent 
    analysis functions.

    The function calculates row income, total income, total units sold,
    product summaries, and category summaries. It also identifies the
    best-selling product, the product with the highest income, and the
    category with the highest income.

    Additionally, it generates Top 5 rankings for best-selling and
    highest-income products. If the optional `ciudad` column is available,
    the function also creates a city summary and identifies the city or cities
    with the highest total income.

    Args:
        validation_result: (Dictionary produced by the validation process.
            It must contain the following keys:

            - `df_valid_rows`: Dataframe containing valid sales records.
            - `total_rows`: Total number of processed records.
            - `total_valid_rows`: Number of records that passed validation.
            - `total_invalid_rows`: Number of records containing validation errors.

    Returns:
        A dictionary containing the following analysis results:

        - `total_rows`: Total number of processed records.
        - `total_valid_rows`: Number of valid records.
        - `total_invalid_rows`: Number of invalid records.
        - `total_income`: Total income generated by valid sales.
        - `total_units_sold`: Total number of units sold.
        - `product_summary`: DataFrame containing aggregated results for each product.
        - `category_summary`: DataFrame containing aggregated results for each category.
        - `best_selling_product`: List containing the product or products with the 
        highest number of units sold.
        - `highest_income_product`: List containing the product or products with the highest
        total income.
        - `highest_income_category`: List containing the category or categories
        with the highest total income.
        - `top_5_best_selling_products`: List containing up to five products with the highest 
            number of units sold.
        - `top_5_highest_income_products`: List containing up to five products with the highest total income.

        When the optional `ciudad` column is available, the result also contains:

        - `city_summary`: DataFrame containing aggregated sales results for each city.
        - `highest_income_city`: List containing the city or cities with the highest total income.


    Raises:
        NoValidRowsError: If no valid sales records are available for analysis.
    """
    df_valid_rows = validation_result["df_valid_rows"]
    total_rows = validation_result["total_rows"]
    total_valid_rows = validation_result["total_valid_rows"]
    total_invalid_rows = validation_result["total_invalid_rows"]
    analysis_result = {
        "total_rows": total_rows,
        "total_valid_rows": total_valid_rows,
        "total_invalid_rows": total_invalid_rows,
    }
    df_analysis = df_valid_rows.copy()
    if len(df_analysis) < 1:
        raise NoValidRowsError()
    df_analysis = create_income_column(df_analysis)
    analysis_result["total_income"] = get_total_income(df_analysis)
    analysis_result["total_units_sold"] = get_total_units_sold(df_analysis)
    analysis_result["product_summary"] = get_product_summary(df_analysis)
    analysis_result["category_summary"] = get_category_summary(df_analysis)
    analysis_result["best_selling_product"] = get_records_with_max_value(analysis_result["product_summary"], "unidades_vendidas")
    analysis_result["highest_income_product"] = get_records_with_max_value(analysis_result["product_summary"], "ingreso_total")
    analysis_result["highest_income_category"] = get_records_with_max_value(analysis_result["category_summary"], "ingreso_total")
    analysis_result["top_5_best_selling_products"] = get_top_5_best_selling_products(analysis_result["product_summary"])
    analysis_result["top_5_highest_income_products"] = get_top_5_highest_income_products(analysis_result["product_summary"])
    if "ciudad" in df_analysis.columns:
        analysis_result["city_summary"] = get_city_summary(df_analysis)
        analysis_result["highest_income_city"] = get_records_with_max_value(analysis_result["city_summary"], "ingreso_total")
    return analysis_result