"""Sales report generation module.

This module converts sales-analysis results, validation errors, and warnings
into a structured human-readable plain-text sales report.

Each report section is generated by an independent helper function to keep
the reporting workflow modular, maintainable, reusable, and easy to extend.

The generated report includes general sales metrics, highest-performing
records, Top 5 product rankings, product and category summaries, detailed
monthly performance metrics, monthly best-selling products, monthly
highest-income categories, validation errors, and validation warnings.

Monthly performance information includes absolute and percentage variations
for income and units sold.

Optional city-based and payment-method-based sections are included when the
corresponding analysis information is available.

The main `generate_report()` function coordinates the helper functions and
combines their output into the complete plain-text report.
"""

from datetime import date
from pathlib import Path
from typing import Dict, Any, List
import pandas as pd
import numpy as np


def get_general_summary(analysis_result: Dict[str, Any]) -> str:
    """Generate the general sales summary section.

    Extracts row totals, total income, and total units sold from the analysis
    result. Monetary values are formatted with thousands separators and two
    decimal places.

    Args:
        analysis_result: Dictionary containing the general metrics produced
            by the sales-analysis process.

    Returns:
        A formatted string containing the general sales summary.
    """
    general_summary = f"""
RESUMEN GENERAL

Total de filas: {analysis_result["total_rows"]}
Filas válidas: {analysis_result["total_valid_rows"]}
Filas inválidas: {analysis_result["total_invalid_rows"]}
Ingreso Total: ${analysis_result["total_income"]:,.2f}
Unidades vendidas: {analysis_result["total_units_sold"]}
"""
    return general_summary
   
def get_best_selling_product(analysis_result: Dict[str, Any]) -> str:
    """Generate the best-selling-product section.

    Reads the product records stored in `best_selling_product` and formats
    their identifiers, names, and total units sold.

    If multiple products share the highest number of units sold, every tied
    product is included in the section.

    Args:
        analysis_result: Dictionary containing the sales-analysis results,
            including the best-selling-product records.

    Returns:
        A formatted string containing all best-selling products.
    """
    list_best_selling_products = analysis_result["best_selling_product"]
    summary = []
    summary.append("PRODUCTO MÁS VENDIDO")
    for best_selling_product in list_best_selling_products:
        summary_product = f"""
{best_selling_product["producto_id"]} - {best_selling_product["producto"]}
Unidades vendidas: {best_selling_product["unidades_vendidas"]}
"""
        summary.append(summary_product)
    return "\n".join(summary)

def get_highest_income(list_income: List[Dict[str, Any]], title: str, column1: str, column2: str | None = None) -> str:
    """Generate a highest-income report section.

    Formats one or more records tied for the highest income using the
    supplied section title and dictionary keys.

    When `column2` is provided, each record displays two descriptive values
    separated by a hyphen. When omitted, only the value stored under
    `column1` is displayed.

    Each record also includes total income and units sold.

    This helper is reused for products, categories, cities, and payment
    methods.

    Args:
        list_income: List of dictionaries containing highest-income records.
        title: Title displayed at the beginning of the section.
        column1: Primary dictionary key used to identify each record.
        column2: Optional secondary dictionary key displayed beside the
            primary value.

    Returns:
        A formatted string containing all highest-income records.
    """
    summary = []
    summary.append(title)
    if column2 is not None:
        for row_income in list_income:
            internal_summary = f"""
{row_income[column1]} - {row_income[column2]}
Ingreso: ${row_income["ingreso_total"]:,.2f}
Unidades vendidas: {row_income["unidades_vendidas"]}
"""
            summary.append(internal_summary)
    else:
        for row_income in list_income:
            internal_summary = f"""
{row_income[column1]}
Ingreso: ${row_income["ingreso_total"]:,.2f}
Unidades Vendidas: {row_income["unidades_vendidas"]}
"""
            summary.append(internal_summary)
    return "\n".join(summary)

def get_top_5(list_top_5: List[Dict[str, Any]], title: str) -> str:
    """Generate a formatted Top 5 product-ranking section.

    Iterates through the supplied ranked product records and displays their
    position, product identifier, product name, units sold, and total income.

    The helper can format different Top 5 rankings by receiving the desired
    section title.

    Args:
        list_top_5: List containing up to five ranked product records.
        title: Title displayed at the beginning of the ranking section.

    Returns:
        A formatted string containing the product ranking.
    """
    summary = []
    summary.append(f"{title}\n")
    for index in range(len(list_top_5)):
        top_5 = list_top_5[index]
        internal_summary = f"""
{index + 1}. {top_5["producto_id"]} - {top_5["producto"]} | Unidades Vendidas: {top_5["unidades_vendidas"]} | Ingreso: ${top_5["ingreso_total"]:,.2f}
""".strip()
        summary.append(internal_summary)
    summary.append("\n".strip())
    return "\n".join(summary)

def get_summary(df: pd.DataFrame, title: str) -> str:
    """Generate a tabular report section from an analysis DataFrame.

    Creates a copy of the supplied DataFrame and formats the `ingreso_total`
    column as currency with thousands separators and two decimal places.

    The formatted DataFrame is converted into plain text without displaying its
    pandas index.

    This helper is reused for product, category, city, and payment-method
    summaries.

    Args:
        df: DataFrame containing an analysis summary with an `ingreso_total`
            column.
        title: Title displayed before the tabular summary.

    Returns:
        A formatted string containing the section title and DataFrame data.
    """
    df_copy = df.copy()
    df_copy["ingreso_total"] = df_copy["ingreso_total"].map(lambda x: f"${x:,.2f}")
    summary = []
    summary.append(title)
    summary.append(f"\n{df_copy.to_string(index=False)}\n")
    return "\n".join(summary)

def get_errors(errors: List[Dict[str, Any]]) -> str:
    """Generate the validation-errors section.

    Sorts validation errors by CSV line number and formats their column, error
    type, message, and original value.

    When an error has no original value, the original-value line is omitted.
    If no errors are available, the section indicates that no validation errors
    were found.

    Args:
        errors: List of dictionaries containing detailed validation errors.

    Returns:
        A formatted string containing the validation errors in ascending
        line-number order.
    """
    summary = []
    summary.append("ERRORES DE VALIDACIÓN")
    if len(errors) < 1:
        summary.append("No se encontraron errores de validación.\n")
        return "\n".join(summary)
    sorted_errors = sorted(errors, key=lambda x: x["line_number"])
    for error in sorted_errors:
        if error["original_value"] == "":
            summary_errors = f"""
- Línea {error["line_number"]} | {error["column"]} | {error["error_type"]} | {error["message"]}"""
        else:
            summary_errors = f"""
- Línea {error["line_number"]} | {error["column"]} | {error["error_type"]} | {error["message"]} 
  Valor original: {error['original_value']}"""
        summary.append(summary_errors)
    summary.append("")
    return "\n".join(summary)

def get_warnings(warnings: List[Dict[str, Any]]) -> str:
    """Generate the validation-warnings section.

    Sorts warnings by their affected product identifier and formats the warning
    type, message, and inconsistent values.

    If no warnings are available, the section indicates that no warnings were
    found.

    Args:
        warnings: List of dictionaries containing non-critical validation
            warnings.

    Returns:
        A formatted string containing the detected warnings.
    """
    summary = []
    summary.append("ADVERTENCIAS")
    if len(warnings) < 1:
        summary.append("No se encontraron advertencias.\n")
        return "\n".join(summary)
    sorted_warnings = sorted(warnings, key=lambda x: x["affected_value"])
    for warning in sorted_warnings:
        summary_warning = f"""
- producto_id {warning["affected_value"]} | {warning["warning_type"]} | {warning["message"]} 
  Detalles: {", ".join(warning["details"])}"""
        summary.append(summary_warning)
    return "\n".join(summary)

def get_sign(number: float | None) -> str:
    """Return the display sign associated with a numeric variation.

    Returns a minus sign for negative values, a plus sign for positive
    values, and an empty string for zero or missing values.

    This helper is used when formatting monthly income and unit variations.

    Args:
        number: Numeric variation value or `None`.

    Returns:
        `"-"` for negative values, `"+"` for positive values, or an empty
        string when the value is zero or unavailable.
    """
    if number is not None and number < 0:
        sign = "-" 
    elif number is not None and number> 0:
        sign = "+"
    else:
        sign = ""
    return sign

def get_monthly_summary(df: pd.DataFrame) -> str:
    """Generate the detailed monthly sales summary section.

    Replaces pandas `NaN` values with `None` and converts the monthly-summary
    DataFrame into a list of dictionaries for individual record formatting.

    For each month, the section displays:

    - `mes`
    - `filas_validas`
    - `unidades_vendidas`
    - `ingreso_total`
    - `crecimiento_ingreso`
    - `crec_ingreso_pct`
    - `crecimiento_unidades`
    - `crec_unidades_pct`

    Positive variations are displayed with a plus sign and negative
    variations with a minus sign.

    Missing growth values, such as those from the first available month, are
    displayed as `N/D`.

    Args:
        df: Monthly-summary DataFrame containing sales totals and growth
            metrics.

    Returns:
        A formatted string containing the detailed monthly sales summary.
    """
    month_dicts = df.replace({np.nan: None}).to_dict(orient="records")
    summary = []
    summary.append("RESUMEN POR MES")
    for month_dict in month_dicts:
        income_sign = get_sign(month_dict["crecimiento_ingreso"])
        units_sign = get_sign(month_dict["crecimiento_unidades"])
        internal_summary = f"""
Mes: {month_dict["mes"]}
Filas válidas: {month_dict["filas_validas"]}
Unidades vendidas: {month_dict["unidades_vendidas"]}
Ingreso total: ${month_dict["ingreso_total"]:,.2f}
Variación de ingreso: {"N/D" if month_dict["crecimiento_ingreso"] is None else f'{income_sign}${abs(month_dict["crecimiento_ingreso"]):,.2f}'}
Variación porcentual de ingreso: {"N/D" if month_dict["crec_ingreso_pct"] is None else f'{income_sign}{abs(month_dict["crec_ingreso_pct"]):,.2f}%'}
Variación de unidades: {"N/D" if month_dict["crecimiento_unidades"] is None else f'{units_sign}{abs(month_dict["crecimiento_unidades"]):,.0f}'}
Variación porcentual de unidades: {"N/D" if month_dict["crec_unidades_pct"] is None else f'{units_sign}{abs(month_dict["crec_unidades_pct"]):,.2f}%'}
"""
        summary.append(internal_summary)
    return "\n".join(summary)

def get_monthly_best_selling_product(df: pd.DataFrame) -> str:
    """Generate the monthly best-selling-product section.

    Replaces pandas missing values with `None` and converts the supplied
    DataFrame into individual records.

    Records are grouped visually by month. The month heading is displayed
    only when the current record belongs to a different month from the
    previous record.

    For each best-selling product, the section displays:

    - Product identifier.
    - Product name.
    - Category.
    - Units sold.
    - Income generated.

    Multiple products can be displayed for the same month when they are tied
    for the highest number of units sold.

    Args:
        df: DataFrame containing monthly best-selling-product records.

    Returns:
        A formatted string containing the best-selling product or products
        for each month.
    """
    month_dicts = df.replace({np.nan: None}).to_dict(orient="records")
    before_month = None
    summary = []
    summary.append("PRODUCTO MÁS VENDIDO POR MES")
    for month_dict in month_dicts:
        if month_dict["mes"] != before_month:
            summary.append(f"\n{month_dict['mes']}")
            before_month = month_dict["mes"]
        internal_summary = f"""
Producto: {month_dict["producto_id"]} - {month_dict["producto"]}
Categoría: {month_dict["categoria"]}
Unidades vendidas: {month_dict["unidades_vendidas"]}
Ingreso generado: ${month_dict["ingreso_total"]:,.2f}"""
        summary.append(internal_summary)
    summary.append("\n".strip())
    return "\n".join(summary)

def get_monthly_highest_income_category(df: pd.DataFrame) -> str:
    """Generate the monthly highest-income-category section.

    Replaces pandas missing values with `None` and converts the supplied
    DataFrame into individual records.

    Records are grouped visually by month. The month heading is displayed
    only when the current record belongs to a different month from the
    previous record.

    For each category, the section displays:

    - Category name.
    - Units sold.
    - Income generated.

    Multiple categories can be displayed for the same month when they are
    tied for the highest income.

    Args:
        df: DataFrame containing monthly highest-income-category records.

    Returns:
        A formatted string containing the highest-income category or
        categories for each month.
    """
    month_dicts = df.replace({np.nan: None}).to_dict(orient="records")
    before_month = None
    summary = []
    summary.append("CATEGORÍA CON MAYOR INGRESO POR MES")
    for month_dict in month_dicts:
        if month_dict["mes"] != before_month:
            summary.append(f"\n{month_dict['mes']}")
            before_month = month_dict["mes"]
        internal_summary = f"""
Categoría: {month_dict["categoria"]}
Unidades vendidas: {month_dict["unidades_vendidas"]}
Ingreso generado: ${month_dict["ingreso_total"]:,.2f} """
        summary.append(internal_summary)
    summary.append("\n".strip())
    return "\n".join(summary)  

def generate_report(
        analysis_result: Dict[str, Any],
        errors: List[Dict[str, Any]],
        warnings: List[Dict[str, Any]],
        source_filename: Path
)-> str:
    """Generate the complete plain-text sales report.

    Creates the report header and includes the original source filename and
    generation date.

    The function coordinates the independent report helpers and combines their
    output into a complete plain-text document.

    The report includes:

    - General sales metrics.
    - Overall best-selling product records.
    - Highest-income product records.
    - Highest-income category records.
    - Top 5 best-selling products.
    - Top 5 highest-income products.
    - Product summary.
    - Category summary.
    - Detailed monthly summary with growth metrics.
    - Monthly best-selling products.
    - Monthly highest-income categories.
    - Validation errors.
    - Validation warnings.

    When city analysis is available, the report also includes the
    highest-income city and complete city summary.

    When payment-method analysis is available, the report also includes the
    highest-income payment method and complete payment-method summary.

    Args:
        analysis_result: Dictionary containing metrics, summaries, rankings,
            growth indicators, and highest-performing records produced by the
            sales-analysis process.
        errors: List of dictionaries containing detailed validation errors.
        warnings: List of dictionaries containing non-critical validation
            warnings.
        source_filename: Path representing the original source CSV file.

    Returns:
        A complete plain-text sales report ready to be displayed or saved.
    """
    summary = []
    summary.append("REPORTE DE VENTAS")
    summary.append(f"""
Archivo de origen: {source_filename.name}
Generado el: {date.today()}""")
    summary.append(get_general_summary(analysis_result))
    summary.append(get_best_selling_product(analysis_result))
    summary.append(get_highest_income(analysis_result["highest_income_product"], "PRODUCTO CON MAYOR INGRESO ", "producto_id", "producto"))
    summary.append(get_highest_income(analysis_result["highest_income_category"], "CATEGORÍA CON MAYOR INGRESO", "categoria"))
    if "highest_income_city" in analysis_result.keys():
        summary.append(get_highest_income(analysis_result["highest_income_city"], "CIUDAD CON MAYOR INGRESO", "ciudad"))
    if "highest_income_payment_method" in analysis_result.keys():
        summary.append(get_highest_income(analysis_result["highest_income_payment_method"], "MÉTODO DE PAGO CON MAYOR INGRESO", "metodo_pago"))
    summary.append(get_top_5(analysis_result["top_5_best_selling_products"], "TOP 5 PRODUCTOS MÁS VENDIDOS"))
    summary.append(get_top_5(analysis_result["top_5_highest_income_products"], "TOP 5 PRODUCTOS CON MAYOR INGRESO"))
    summary.append(get_summary(analysis_result["product_summary"], "RESUMEN POR PRODUCTO"))
    summary.append(get_summary(analysis_result["category_summary"], "RESUMEN POR CATEGORÍA"))
    if "city_summary" in analysis_result.keys():
        summary.append(get_summary(analysis_result["city_summary"], "RESUMEN POR CIUDAD"))
    if "payment_method_summary" in analysis_result.keys():
        summary.append(get_summary(analysis_result["payment_method_summary"], "RESUMEN POR MÉTODO DE PAGO"))
    summary.append(get_monthly_summary(analysis_result["monthly_summary"]))
    summary.append(get_monthly_best_selling_product(analysis_result["monthly_best_selling_product"]))
    summary.append(get_monthly_highest_income_category(analysis_result["monthly_highest_income_category"]))
    summary.append(get_errors(errors))
    summary.append(get_warnings(warnings))
    return "\n".join(summary)
